### ISSUE TITLE
feat: implement skill component

### ISSUE THREAD

**Issue by rudeh1253** [rudeh1253/webmapia#15]
## Overview
A skill component has responsibility to record who has activated skill, process skills activated at that NIGHT, and outputs the result.

## TODO
- [x] Store skill activation records in model.
- [x] Activate a skill for that round.
- [ ] Logic to process a series of skills activated.
